[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name="mergepdf"
version = "0.1.10"
requires-python = ">= 3.7"
readme = "README.md"

[project.scripts]
mergepdf = "mergepdf.cli:main"